server:
  port: 8080
#  servlet:
#     context-path: /dev
spring:
  datasource:
       url: jdbc:mysql://localhost:3306/usedbooksystem?serverTimezone=GMT%2b8&useUnicode=true&&allowMultiQueries=true&characterEncoding=utf-8
       username: root
       password:
       driver-class-name: com.mysql.cj.jdbc.Driver
       type: com.alibaba.druid.pool.DruidDataSource
       initialSize: 5
       maxActive: 50
       minIdle: 5
       # Validate the connection before borrowing it from the pool.
       test-on-borrow: true
       test-while-idle: true
       validation-query: SELECT 1 FROM DUAL
       time-between-eviction-runs-millis: 3600000
       min-evictable-idle-time-millis: 1800000

mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.lixia.vehicleapp
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
